server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lock?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: tangguo
    driver-class-name: com.mysql.jdbc.Driver

